name: Reproducible Bug Report
description: |
  Please provide reproduction steps, your issue *will be closed without review* if reproduction steps are omitted. Before submitting an issue, please first
   - search through github to confirm that it is not a duplicate.
   - search discord to see if someone else has already answered your question.
   - search the [docs](https://tamagui.dev/docs/intro/introduction) to see if the issue has been documented.
   - google error messages to see if the issue has been reported elsewhere.
   - take a moment to think about any additional context might be helpful to provide for the human on the other end of the screen who is trying to help you. We appreciate you taking the time to help make Tamagui better!
labels: [Bug]
body:
  - type: textarea
    attributes:
      label: Current Behavior
      description: Describe what's happening in 1-2 sentences.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Tamagui Version
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Platform (Web, iOS, Android)
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      render: markdown
      description: |
        - If you don't include reproduction, the issue will be automatically closed.
        - You can always create a new Tamagui starter using `npm create tamagui` and then push that somewhere.
        - Be sure to have the reproduction be in its own separate commit.
        - For simpler bugs you can fork [this CodeSandbox](https://codesandbox.io/p/sandbox/github/tamagui/tamagui/tree/master/starters/next-expo-solito) to reproduce the issue.
        - For simple web bugs, try [this one](https://github.com/tamagui/issue-template-webpack) and run `yarn upgrade` to update tamagui to latest.
        - For native-only bugs, fork this repo and use `apps/kitchen-sink` to reproduce the bug. Once reproduced, submit a PR with the title `[Issue] ...`
    validations:
      required: true
  - type: textarea
    attributes:
      label: System Info
      render: markdown
      description: |
        - Output of `npx envinfo --system --npmPackages --binaries --browsers`
