name: 'Install'
description: 'Install and pre-build'
inputs:
  git_crypt_key:
    description: 'Git crypt key for unlocking secrets'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        registry-url: 'https://registry.npmjs.org'

    - name: Unlock secrets
      uses: sliteteam/github-action-git-crypt-unlock@1.2.0
      env:
        GIT_CRYPT_KEY: ${{ inputs.git_crypt_key }}

    - name: install yarn
      shell: bash
      run: npm i yarn -g

    - name: Install Dependencies
      shell: bash
      run: yarn install

    - name: Build JS
      shell: bash
      run: yarn build:js
