name: Release

on:
  push:
    paths-ignore:
      - 'assets/**'
      - '.vscode/**'
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@master
        with:
          node-version: 16.x

      - name: install yarn
        run: |
          npm i yarn -g
          yarn set version stable

      # - uses: c-hive/gha-yarn-cache@v2

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build JS
        run: yarn build:js

      - name: Build Site
        run: |
          yarn --cwd packages/site next:build
          yarn --cwd packages/site next:export

      # - name: Create Release Pull Request or Publish to npm
      #   id: changesets
      #   uses: changesets/action@master
      #   with:
      #     # This expects you to have a script called release which does a build for your packages and calls changeset publish
      #     publish: yarn ci:release
      #     version: yarn ci:version
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./packages/site/out
          cname: tamagui.dev
