name: Release

on:
  push:
    paths-ignore:
      - 'assets/**'
      - '.vscode/**'
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@master
        with:
          node-version: 16.x

      - name: install yarn
        run: |
          npm i yarn -g
          yarn set version 3.2.0

      - name: Install Dependencies
        run: |
          YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install

      - name: Build JS
        run: yarn build:js

      - name: Build Site
        run: |
          yarn --cwd packages/site vercel:build

      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./packages/site/out
          cname: tamagui.dev
