name: Release

on:
  push:
    paths-ignore:
      - 'assets/**'
      - '.vscode/**'
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/install

      - name: Check
        run: yarn check

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Release Site
        uses: ./.github/actions/release-site

      # test this later...
      # - name: Publish Beta
      #   run: yarn release:beta --ci
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
