name: Bento

on:
  push:
    paths:
      - "apps/bento/**"
      - "apps/site/scripts/build-bento.js"
      - "apps/site/scripts/upload-bento.js"
    branches:
      - master

jobs:
  build-and-upload:
    name: Build & Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unlock Secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Install
        uses: ./.github/actions/install

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Link Vercel Project
        run: cd apps/site && vercel link --project site --scope=tamagui --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Vercel Environment Information
        run: cd apps/site && vercel env pull .env.local --environment production --scope=tamagui --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Bento Components
        run: cd apps/site && yarn build:bento

      - name: Upload To Supabase
        run: cd apps/site && yarn upload-bento
